services:
  frontend:
    build: ./mobile-shop
    ports:
      - "5173:5173"
    volumes:
      - ./mobile-shop:/app
      - /app/node_modules
    depends_on:
      - backend
      - json-server
    command: npm run dev

  backend:
    build: ./Server
    ports:
      - "4242:4242"
    volumes:
      - ./Server:/app
      - /app/node_modules
    environment:
      - PORT=4242
    command: npm run dev

  json-server:
      build: ./json-server
      ports:
        - "3000:3000"
      volumes:
        - ./json-server:/app
        - /app/node_modules
      command: npm run dev